config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/support', to: 'pages#support'

  get "healthcheck" => "rails/health#show", as: :rails_health_check

  scope via: :all do
    get '/404', to: 'errors#not_found'
    get '/422', to: 'errors#unprocessable_entity'
    get '/429', to: 'errors#too_many_requests'
    get '/500', to: 'errors#internal_server_error'
  end

  resources :cities, only: %i[index create show]

  # omniauth sign-in
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/sign-in', to: 'sessions#new'
  get '/sign-out', to: 'sessions#destroy'

  # one time password
  get '/otp-sign-in', to: 'otp_sessions#new'
  post '/otp-sign-in', to: 'otp_sessions#create'
  get '/otp-sign-in/code', to: 'otp_sessions#request_code'
  post '/otp-sign-in/verify', to: 'otp_sessions#verify_code'

  constraints -> { Rails.application.config.enable_personas } do
    resources 'personas', only: %i[index]
  end

  post 'auth/:provider/callback', to: 'sessions#create'

  get '/admin', to: 'admin/teachers#index'

  namespace :admin do
    constraints -> { Rails.application.config.enable_blazer } do
      mount Blazer::Engine, at: "blazer"
    end

    resources :users, only: %i[index] do
    end

    resources :appropriate_bodies, only: %i[index], path: 'appropriate-bodies' do
    end

    resources :schools, only: %i[index show], param: :urn do
    end

    resources :teachers, only: %i[index show] do
    end
  end

  resource :appropriate_bodies, only: %i[show], path: 'appropriate-body', as: 'ab_landing', controller: 'appropriate_bodies/landing'
  namespace :appropriate_bodies, path: 'appropriate-body', as: 'ab' do
    resources :teachers, only: %i[show index], controller: 'teachers', param: 'trn' do
      resource :release_ect, only: %i[new create show], path: 'release', controller: 'teachers/release_ect'
      resource :record_passed_outcome, only: %i[new create show], path: 'record-passed-outcome', controller: 'teachers/record_passed_outcome'
      resource :record_failed_outcome, only: %i[new create show], path: 'record-failed-outcome', controller: 'teachers/record_failed_outcome'

      resources :extensions, controller: 'teachers/extensions', only: %i[show edit update index new create]
      resources :initial_teacher_training_records, path: 'itt-data', controller: 'teachers/initial_teacher_training_records', only: :index
    end

    namespace :claim_an_ect, path: 'claim-an-ect' do
      resource :find_ect, only: %i[new create], path: 'find-ect', controller: '/appropriate_bodies/claim_an_ect/find_ect', as: 'find'
      resources :check_ect, only: %i[edit update], path: 'check-ect', controller: '/appropriate_bodies/claim_an_ect/check_ect', as: 'check'
      resources :register_ect, only: %i[edit update show], path: 'register-ect', controller: '/appropriate_bodies/claim_an_ect/register_ect', as: 'register'

      namespace :errors do
        get 'induction-already-completed/:id', to: '/appropriate_bodies/claim_an_ect/errors#induction_already_completed', as: 'already_complete'
        get 'induction-with-another-appropriate-body/:id', to: '/appropriate_bodies/claim_an_ect/errors#induction_with_another_appropriate_body', as: 'another_ab'
        get 'no-qts/:id', to: '/appropriate_bodies/claim_an_ect/errors#no_qts', as: 'no_qts'
        get 'prohibited-from-teaching/:id', to: '/appropriate_bodies/claim_an_ect/errors#prohibited_from_teaching', as: 'prohibited'
        get 'exempt/:id', to: '/appropriate_bodies/claim_an_ect/errors#exempt', as: 'exempt'
        get 'completed/:id', to: '/appropriate_bodies/claim_an_ect/errors#completed', as: 'completed'
      end
    end
  end

  namespace :migration do
    resources :migrations, only: %i[index create], path: "/" do
      collection do
        get ":model/failures", to: "failures#index", as: :failures
        get "download_report/:model", action: :download_report, as: :download_report
        post "reset", action: :reset, as: :reset
      end
    end
    get "teachers/:trn", to: "teachers#show", as: :teacher_details
  end

  namespace :schools do
    get "/home/ects", to: "home#index", as: :ects_home

    namespace :register_ect_wizard, path: "register-ect" do
      get "what-you-will-need", as: :start, action: :start

      get "find-ect", action: :new
      post "find-ect", action: :create

      get "national-insurance-number", action: :new
      post "national-insurance-number", action: :create

      get "trn-not-found", action: :new
      get "not-found", action: :new

      get "induction-completed", action: :new
      get "induction-exempt", action: :new

      get "review-ect-details", action: :new
      post "review-ect-details", action: :create

      get "email-address", action: :new
      post "email-address", action: :create

      get "check-answers", action: :new
      post "check-answers", action: :create

      get "confirmation", action: :new
    end
  end

  namespace :schools, path: :school do
    namespace :register_mentor_wizard, path: "register-mentor" do
      get "what-you-will-need", as: :start, action: :start

      get "find-mentor", action: :new
      post "find-mentor", action: :create

      get "national-insurance-number", action: :new
      post "national-insurance-number", action: :create

      get "no-trn", action: :new
      get "trn-not-found", action: :new
      get "not-found", action: :new

      get "review-mentor-details", action: :new
      post "review-mentor-details", action: :create

      get "email-address", action: :new
      post "email-address", action: :create

      get "check-answers", action: :new
      post "check-answers", action: :create

      get "confirmation", action: :new
    end
  end
end

app/models/gias/school.rb
class GIAS::School < ApplicationRecord
  self.table_name = "gias_schools"
  self.ignored_columns = %i[search]

  # Enums
  enum :funding_eligibility,
       { eligible_for_fip: "eligible_for_fip",
         eligible_for_cip: "eligible_for_cip",
         ineligible: "ineligible" },
       prefix: :funding,
       validate: true

  enum :status,
       { open: "open",
         closed: "closed",
         proposed_to_close: "proposed_to_close",
         proposed_to_open: "proposed_to_open" },
       suffix: true,
       validate: true

  # Associations
  has_one :school, foreign_key: :urn, primary_key: :urn, inverse_of: :gias_school
  has_many :gias_school_links, class_name: "GIAS::SchoolLink", foreign_key: :urn, dependent: :destroy, inverse_of: :from_gias_school

  # Validations
  validates :establishment_number,
            numericality: { only_integer: true }

  validates :local_authority_code,
            numericality: { only_integer: true }

  validates :name,
            presence: true

  validates :type_name,
            inclusion: {
              in: GIAS::Types::ALL_TYPES,
              message: "is not a valid school type",
            }

  validates :ukprn,
            numericality: {
              only_integer: true,
              allow_nil: true,
            },
            uniqueness: {
              allow_nil: true,
            }

  validates :urn,
            numericality: {
              only_integer: true,
            },
            uniqueness: true

  # Scopes
  scope :search, ->(q) { where("gias_schools.search @@ websearch_to_tsquery('unaccented', ?)", q) }

  # Instance Methods
  def closed?
    !open?
  end

  def open?
    open_status? || proposed_to_close_status?
  end
end

app/models/migration/school.rb
module Migration
  class School < Migration::Base
    has_many :school_cohorts
    has_many :partnerships
  end
end

app/models/school.rb
class School < ApplicationRecord
  # Associations
  belongs_to :gias_school, class_name: "GIAS::School", foreign_key: :urn, inverse_of: :school

  has_many :ect_at_school_periods, inverse_of: :school
  has_many :mentor_at_school_periods, inverse_of: :school

  has_many :current_mentors, -> { ongoing }, class_name: "MentorAtSchoolPeriod"

  has_many :ect_teachers, -> { distinct }, through: :ect_at_school_periods, source: :teacher
  has_many :mentor_teachers, -> { distinct }, through: :mentor_at_school_periods, source: :teacher

  # Validations
  validates :urn,
            presence: true,
            uniqueness: true

  # Scopes
  scope :search, ->(q) { includes(:gias_school).merge(GIAS::School.search(q)) }

  # Instance Methods
  delegate :address_line1,
           :address_line2,
           :address_line3,
           :administrative_district_name,
           :closed_on,
           :establishment_number,
           :funding_eligibility,
           :induction_eligibility,
           :in_england,
           :local_authority_code,
           :local_authority_name,
           :name,
           :primary_contact_email,
           :opened_on,
           :phase_name,
           :postcode,
           :type_name,
           :secondary_contact_email,
           :section_41_approved,
           :status,
           :ukprn,
           :website,
           to: :gias_school

  def to_param
    urn
  end
end

app/controllers/admin/migration/schools_controller.rb
class Admin::Migration::SchoolsController < AdminController
  def index
  end

  def show
  end
end

app/controllers/admin/schools_controller.rb
module Admin
  class SchoolsController < AdminController
    layout "full"

    before_action :config_search

    def index
      @pagy, @schools = pagy(Schools::Search.new(@q).call)
    end

    def show
      @school = School.includes(:gias_school).find_by(urn: school_params[:urn])
    end

  private

    def schools_params
      params.permit(:page, :q, :urn)
    end

    def school_params
      params.permit(:page, :q, :urn)
    end

    def config_search
      @q = schools_params[:q]
      @page = schools_params[:page] || 1
    end
  end
end

app/controllers/schools/home_controller.rb
module Schools
  class HomeController < SchoolsController
    layout "full"

    def index
      teacher_service = Schools::Teacher.new(school.id)
      @relationships = teacher_service.fetch_etcs_and_mentors
    end
  end
end

app/controllers/schools/register_ect_wizard_controller.rb
# frozen_string_literal: true

module Schools
  class RegisterECTWizardController < SchoolsController
    before_action :initialize_wizard, only: %i[new create]
    before_action :reset_wizard, only: :new

    FORM_KEY = :register_ect_wizard
    WIZARD_CLASS = Schools::RegisterECTWizard::Wizard.freeze

    def start
    end

    def new
      render current_step
    end

    def create
      if @wizard.save!
        redirect_to @wizard.next_step_path
      else
        render current_step
      end
    end

  private

    def initialize_wizard
      @wizard = WIZARD_CLASS.new(
        current_step:,
        step_params: params,
        store:
      )
      @ect = @wizard.ect
    end

    def current_step
      request.path.split("/").last.underscore.to_sym.tap do |step_from_path|
        return :not_found unless WIZARD_CLASS.step?(step_from_path)
      end
    end

    def reset_wizard
      @wizard.reset if current_step == :find_ect
    end

    def store
      @store ||= SessionRepository.new(session:, form_key: FORM_KEY).tap do |store|
        store.update(school_urn: @school.urn)
      end
    end
  end
end

app/controllers/schools/register_mentor_wizard_controller.rb
module Schools
  class RegisterMentorWizardController < SchoolsController
    before_action :initialize_wizard, only: %i[new create]
    before_action :reset_wizard, only: :new

    FORM_KEY = :register_mentor_wizard
    WIZARD_CLASS = Schools::RegisterMentorWizard::Wizard.freeze

    def start
      @ect = ECTAtSchoolPeriod.find(params[:ect_id])
      session[:register_mentor_for_ect_id] = @ect.id
      @ect_name = Teachers::Name.new(@ect.teacher).full_name
    end

    def new
      render current_step
    end

    def create
      if @wizard.save!
        redirect_to @wizard.next_step_path
      else
        render current_step
      end
    end

  private

    def initialize_wizard
      @wizard = WIZARD_CLASS.new(
        current_step:,
        step_params: params,
        ect_id: session[:register_mentor_for_ect_id],
        store:
      )
      @ect_name = Teachers::Name.new(@wizard.ect.teacher).full_name
      @mentor = @wizard.mentor
    end

    def current_step
      request.path.split("/").last.underscore.to_sym.tap do |step_from_path|
        return :not_found unless WIZARD_CLASS.step?(step_from_path)
      end
    end

    def reset_wizard
      @wizard.reset if current_step == :find_mentor
    end

    def store
      @store ||= SessionRepository.new(session:, form_key: FORM_KEY).tap do |store|
        store.update(school_urn: @school.urn)
      end
    end
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  include Authorisation

  before_action :set_school

private

  attr_reader :school

  def authorised?
    # FIXME: make this work with DfE Sign-in
    current_user.email == 'admin@example.com' || current_user.school_user?
  end

  def set_school
    # This is temporary. 'School' will be set once DfE signin hooked up
    # School in the session or first school with ects but no mentors or first school
    @school = (school_from_session || first_school_with_no_mentors_but_ects || first_school)
  end

  def school_from_session
    School.joins(:gias_school).find_by_urn(current_user.school_urn)
  end

  def first_school_with_no_mentors_but_ects
    School.joins(:gias_school, :ect_at_school_periods)
          .left_joins(:mentor_at_school_periods)
          .where.not(ect_at_school_periods: { id: nil })
          .where(mentor_at_school_periods: { id: nil })
          .first
  end

  def first_school
    School.joins(:gias_school).first
  end
end

app/helpers/school/home_helper.rb
module School::HomeHelper
  def link_to_ect(name)
    govuk_link_to(name,
                  '#',
                  no_visited_state: true)
  end

  def in_progress_status
    govuk_tag(text: 'In progress', colour: 'green')
  end
end

app/helpers/school/register_ect_helper.rb
module School::RegisterECTHelper
  def link_to_ect(name)
    govuk_link_to(name,
                  '#',
                  no_visited_state: true)
  end

  def in_progress_status
    govuk_tag(text: 'In progress', colour: 'green')
  end
end

app/helpers/schools/home_helper.rb
module Schools::HomeHelper
  def link_to_assign_mentor(ect)
    govuk_warning_text(text: "You must #{assign_or_create_mentor_link(ect)} for this ECT.".html_safe)
  end

private

  def assign_or_create_mentor_link(ect)
    govuk_link_to("assign a mentor or register a new one", assign_or_create_mentor_path(ect), no_visited_state: true)
  end

  def assign_or_create_mentor_path(ect)
    return new_schools_ect_mentorship_path(ect) if eligible_mentors_for_ect?(ect)

    schools_register_mentor_wizard_start_path(ect_id: ect.id)
  end

  def eligible_mentors_for_ect?(ect)
    Schools::EligibleMentors.new(ect.school).for_ect(ect).exists?
  end
end

app/views/schools/register_mentor_wizard/check_answers.html.erb
<% page_data(title: "Check your answers and confirm mentor details", backlink_href: schools_register_mentor_wizard_email_address_path) %>

<%= govuk_summary_list do |summary_list|
  summary_list.with_row do |row|
    row.with_key(text: 'Teacher reference number (TRN)')
    row.with_value(text: @mentor.trn)
  end

  summary_list.with_row do |row|
    row.with_key(text: 'Name')
    row.with_value(text: @mentor.full_name)
  end

  summary_list.with_row do |row|
    row.with_key(text: 'Email address')
    row.with_value(text: @mentor.email)
  end
end %>

<%= govuk_inset_text(text: "#{@mentor.full_name} will mentor #{@ect_name}") %>

<%= form_with(model: @wizard.current_step, url: @wizard.current_step_path) do |f| %>
  <%= content_for(:error_summary) { f.govuk_error_summary } %>

  <%= f.govuk_submit "Confirm details" %>
<% end %>

app/views/schools/register_mentor_wizard/confirmation.md.erb
---
title: You've assigned <%= @mentor.full_name %> as a mentor
header: false
---

<%= govuk_panel(title_text: "You've assigned #{@mentor.full_name} as a mentor") do %>
for
<br>
<strong><%= @ect_name %></strong>
<% end %>

You have successfully registered <%= @ect_name %> for training.

### What happens next

We'll email <%= @mentor.full_name %> to confirm you have registered them.

They do not need to provide us with any further details.

<%= govuk_link_to "Back to ECTs", schools_ects_home_path %>

app/views/schools/register_mentor_wizard/email_address.html.erb
<% page_data(title: "What is #{@mentor.full_name}'s email address?", error: @wizard.current_step.errors.present?, backlink_href: schools_register_mentor_wizard_review_mentor_details_path) %>

<p class="govuk-body">We need an email so we can ask for their consent to share their details if needed for
  training.</p>

<%= form_with(model: @wizard.current_step, url: @wizard.current_step_path) do |f| %>
  <%= content_for(:error_summary) { f.govuk_error_summary } %>

  <%= f.govuk_email_field(:email, label: { text: "Email address", hidden: true, class: 'govuk-!-margin-bottom-4' }) %>

  <%= f.govuk_submit "Continue" %>
<% end %>

app/views/schools/register_mentor_wizard/find_mentor.html.erb
<% page_data(title: "Find a mentor", error: @wizard.current_step.errors.present?, backlink_href: schools_register_mentor_wizard_start_path(ect_id: @wizard.ect.id)) %>

<p class="govuk-body">Enter the mentor's teacher reference number and date of birth to find them.</p>

<%= form_with(model: @wizard.current_step, url: @wizard.current_step_path) do |f| %>
  <%= content_for(:error_summary) { f.govuk_error_summary } %>

  <%= f.govuk_number_field(
        :trn,
        label: { text: "Teacher reference number (TRN)", size: "m" },
        hint: { text: "This unique ID is usually 7 digits long, for example 4567814. It may also include letters or a slash, for example RP99/12345. It can be found on their payslip, teaching contract or registration document from the GTCE.", size: "s" },
        extra_letter_spacing: true
      )
  %>

  <%= f.govuk_date_field :date_of_birth,
                         date_of_birth: true,
                         width: "two-thirds",
                         legend: { text: 'Date of birth', size: "m", tag: "h3" },
                         hint: { text: "For example, 31 3 1980" }
  %>

  <%= f.govuk_submit "Continue" %>
<% end %>

<p><%= govuk_link_to("They do not have a TRN", schools_register_mentor_wizard_no_trn_path) %></p>


<%= render TestGuidanceComponent.new do |component| %>
  <% component.with_trs_example_teacher_details %>
<% end %>

app/views/schools/register_mentor_wizard/national_insurance_number.html.erb
<% page_data(title: "We cannot find the mentor's details", error: @wizard.current_step.errors.present?, backlink_href: schools_register_mentor_wizard_find_mentor_path) %>

<p class="govuk-body">We cannot find a match with the details you've given. You'll need to provide more information about the mentor to help us locate them.</p>

<%= form_with(model: @wizard.current_step, url: @wizard.current_step_path) do |f| %>
  <%= content_for(:error_summary) { f.govuk_error_summary } %>

  <%= f.govuk_text_field(
        :national_insurance_number,
        label: { text: "National Insurance Number", size: "m" },
        hint: { text: "Enter the mentor's National Insurance number. It's on their National Insurance card, benefit letter, payslip or P60. For example, 'QQ 12 34 56 D'.", size: "s" },
        )
  %>

  <%= f.govuk_submit "Continue" %>
<% end %>

<%= render TestGuidanceComponent.new do |component| %>
  <% component.with_trs_example_teacher_details %>
<% end %>

app/views/schools/register_mentor_wizard/no_trn.md.erb
---
title: You cannot register a mentor without a TRN
---

If they:

- had a TRN but cannot find it, ask them to use the [Find a lost TRN service](https://find-a-lost-trn.education.gov.uk/start)
- have never had one, they'll need to [request a TRN](https://www.gov.uk/guidance/teacher-reference-number-trn#if-youre-a-mentor-for-a-trainee-or-early-career-teacher)

[Return to your ECTs](<%= schools_ects_home_path %>)

app/views/schools/register_mentor_wizard/not_found.md.erb
---
title: We're unable to match the mentor with the details you provided
---

You can check the mentor's teacher reference number (TRN) is accurate by [reviewing their teacher record](https://www.gov.uk/guidance/check-a-teachers-record).

Alternatively, you can ask the mentor to check their TRN by using the [Find a lost TRN service](https://find-a-lost-trn.education.gov.uk/start).

<%= govuk_button_link_to("Try again", schools_register_mentor_wizard_find_mentor_path) %>

app/views/schools/register_mentor_wizard/review_mentor_details.html.erb
<% page_data(title: "Check mentor details", backlink_href: schools_register_mentor_wizard_find_mentor_path) %>

<p>There is a teacher record that matches the details you have provided.</p>

<%= govuk_summary_list do |summary_list|
  summary_list.with_row do |row|
    row.with_key(text: 'Name')
    row.with_value(text: @mentor.full_name)
  end

  summary_list.with_row do |row|
    row.with_key(text: 'Teacher Reference Number (TRN)')
    row.with_value(text: @mentor.trn)
  end

  if @mentor.matches_trs_dob?
    summary_list.with_row do |row|
      row.with_key(text: 'Date of birth')
      row.with_value(text: @mentor.govuk_date_of_birth)
    end
  else
    summary_list.with_row do |row|
      row.with_key(text: 'National insurance number')
      row.with_value(text: @mentor.national_insurance_number)
    end
  end
end %>

<%= form_with(model: @wizard.current_step, url: @wizard.current_step_path) do |f| %>
  <%= content_for(:error_summary) { f.govuk_error_summary } %>

  <%= f.govuk_submit "Confirm and continue" %>
<% end %>

<div class="govuk-inset-text">
  If this is not the person you intended to register as a mentor, go back
  and <%= govuk_link_to("check details", schools_register_mentor_wizard_find_mentor_path) %>.
</div>

app/views/schools/register_mentor_wizard/start.html.erb
<% page_data(title: "What you'll need to add a new mentor for #{@ect_name}", error: false, backlink_href: schools_ects_home_path) %>

<p class="govuk-body">You must provide the mentor's:</p>
<ul class="govuk-list govuk-list--bullet">
  <li>name</li>
  <li>teacher reference number (TRN)</li>
  <li>date of birth</li>
  <li>email address</li>
</ul>

<p class="govuk-body">You may also need to tell us about the mentor’s training programme.</p>

<%= govuk_button_link_to("Continue", schools_register_mentor_wizard_find_mentor_path) %>

app/views/schools/register_mentor_wizard/trn_not_found.md.erb
---
title: We're unable to match the mentor with the details you provided
---

You can check the mentor's teacher reference number (TRN) is accurate by [reviewing their teacher record](https://www.gov.uk/guidance/check-a-teachers-record)
Alternatively, you can ask the mentor to check their TRN by using the [Find a lost TRN service](https://find-a-lost-trn.education.gov.uk/start)

<%= govuk_button_link_to("Try again", schools_register_mentor_wizard_find_mentor_path) %>