config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/support', to: 'pages#support'

  get "healthcheck" => "rails/health#show", as: :rails_health_check

  scope via: :all do
    get '/404', to: 'errors#not_found'
    get '/422', to: 'errors#unprocessable_entity'
    get '/429', to: 'errors#too_many_requests'
    get '/500', to: 'errors#internal_server_error'
  end

  resources :cities, only: %i[index create show]

  # omniauth sign-in
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/sign-in', to: 'sessions#new'
  get '/sign-out', to: 'sessions#destroy'

  # one time password
  get '/otp-sign-in', to: 'otp_sessions#new'
  post '/otp-sign-in', to: 'otp_sessions#create'
  get '/otp-sign-in/code', to: 'otp_sessions#request_code'
  post '/otp-sign-in/verify', to: 'otp_sessions#verify_code'

  constraints -> { Rails.application.config.enable_personas } do
    resources 'personas', only: %i[index]
  end

  post 'auth/:provider/callback', to: 'sessions#create'

  get '/admin', to: 'admin/teachers#index'

  namespace :admin do
    constraints -> { Rails.application.config.enable_blazer } do
      mount Blazer::Engine, at: "blazer"
    end

    resources :users, only: %i[index] do
    end

    resources :appropriate_bodies, only: %i[index], path: 'appropriate-bodies' do
    end

    resources :schools, only: %i[index show], param: :urn do
    end

    resources :teachers, only: %i[index show] do
    end
  end

  resource :appropriate_bodies, only: %i[show], path: 'appropriate-body', as: 'ab_landing', controller: 'appropriate_bodies/landing'
  namespace :appropriate_bodies, path: 'appropriate-body', as: 'ab' do
    resources :teachers, only: %i[show index], controller: 'teachers', param: 'trn' do
      resource :release_ect, only: %i[new create show], path: 'release', controller: 'teachers/release_ect'
      resource :record_passed_outcome, only: %i[new create show], path: 'record-passed-outcome', controller: 'teachers/record_passed_outcome'
      resource :record_failed_outcome, only: %i[new create show], path: 'record-failed-outcome', controller: 'teachers/record_failed_outcome'

      resources :extensions, controller: 'teachers/extensions', only: %i[show edit update index new create]
      resources :initial_teacher_training_records, path: 'itt-data', controller: 'teachers/initial_teacher_training_records', only: :index
    end

    namespace :claim_an_ect, path: 'claim-an-ect' do
      resource :find_ect, only: %i[new create], path: 'find-ect', controller: '/appropriate_bodies/claim_an_ect/find_ect', as: 'find'
      resources :check_ect, only: %i[edit update], path: 'check-ect', controller: '/appropriate_bodies/claim_an_ect/check_ect', as: 'check'
      resources :register_ect, only: %i[edit update show], path: 'register-ect', controller: '/appropriate_bodies/claim_an_ect/register_ect', as: 'register'

      namespace :errors do
        get 'induction-already-completed/:id', to: '/appropriate_bodies/claim_an_ect/errors#induction_already_completed', as: 'already_complete'
        get 'induction-with-another-appropriate-body/:id', to: '/appropriate_bodies/claim_an_ect/errors#induction_with_another_appropriate_body', as: 'another_ab'
        get 'no-qts/:id', to: '/appropriate_bodies/claim_an_ect/errors#no_qts', as: 'no_qts'
        get 'prohibited-from-teaching/:id', to: '/appropriate_bodies/claim_an_ect/errors#prohibited_from_teaching', as: 'prohibited'
        get 'exempt/:id', to: '/appropriate_bodies/claim_an_ect/errors#exempt', as: 'exempt'
        get 'completed/:id', to: '/appropriate_bodies/claim_an_ect/errors#completed', as: 'completed'
      end
    end
  end

  namespace :migration do
    resources :migrations, only: %i[index create], path: "/" do
      collection do
        get ":model/failures", to: "failures#index", as: :failures
        get "download_report/:model", action: :download_report, as: :download_report
        post "reset", action: :reset, as: :reset
      end
    end
    get "teachers/:trn", to: "teachers#show", as: :teacher_details
  end

  namespace :schools do
    get "/home/ects", to: "home#index", as: :ects_home

    namespace :register_ect_wizard, path: "register-ect" do
      get "what-you-will-need", as: :start, action: :start

      get "find-ect", action: :new
      post "find-ect", action: :create

      get "national-insurance-number", action: :new
      post "national-insurance-number", action: :create

      get "trn-not-found", action: :new
      get "not-found", action: :new

      get "induction-completed", action: :new
      get "induction-exempt", action: :new

      get "review-ect-details", action: :new
      post "review-ect-details", action: :create

      get "email-address", action: :new
      post "email-address", action: :create

      get "check-answers", action: :new
      post "check-answers", action: :create

      get "confirmation", action: :new
    end
  end

  namespace :schools, path: :school do
    namespace :register_mentor_wizard, path: "register-mentor" do
      get "what-you-will-need", as: :start, action: :start

      get "find-mentor", action: :new
      post "find-mentor", action: :create

      get "national-insurance-number", action: :new
      post "national-insurance-number", action: :create

      get "no-trn", action: :new
      get "trn-not-found", action: :new
      get "not-found", action: :new

      get "review-mentor-details", action: :new
      post "review-mentor-details", action: :create

      get "email-address", action: :new
      post "email-address", action: :create

      get "check-answers", action: :new
      post "check-answers", action: :create

      get "confirmation", action: :new
    end
  end
end

app/models/migration/appropriate_body.rb
module Migration
  class AppropriateBody < Migration::Base
    has_many :induction_records
    has_many :school_cohorts
  end
end

app/models/migration/base.rb
module Migration
  class Base < ApplicationRecord
    self.abstract_class = true

    connects_to database: { reading: :legacy, writing: :legacy } unless Rails.env.test?

    def readonly?
      !Rails.env.test? # allow factories in test
    end
  end
end

app/models/migration/cohort.rb
module Migration
  class Cohort < Migration::Base
  end
end

app/models/migration/core_induction_programme.rb
module Migration
  class CoreInductionProgramme < Migration::Base
  end
end

app/models/migration/delivery_partner.rb
module Migration
  class DeliveryPartner < Migration::Base
    default_scope { where(discarded_at: nil) }

    has_many :partnerships
  end
end

app/models/migration/induction_programme.rb
module Migration
  class InductionProgramme < Migration::Base
    belongs_to :school_cohort
    belongs_to :partnership, optional: true
    belongs_to :core_induction_programme, optional: true
    has_many :induction_records
  end
end

app/models/migration/induction_record.rb
module Migration
  class InductionRecord < Migration::Base
    belongs_to :participant_profile
    belongs_to :induction_programme
    belongs_to :appropriate_body
    belongs_to :mentor_profile, class_name: "Migration::ParticipantProfile"
    belongs_to :schedule
  end
end

app/models/migration/lead_provider.rb
module Migration
  class LeadProvider < Migration::Base
    has_many :partnerships
  end
end

app/models/migration/mentorship_period_data.rb
module Migration
  # NOTE: this is a PORO to help with collating mentorship period data when processing InductionRecords
  class MentorshipPeriodData
    attr_accessor :mentor_teacher, :start_date, :end_date, :start_source_id, :end_source_id

    def initialize(mentor_teacher:, start_date:, end_date:, start_source_id:, end_source_id:)
      @mentor_teacher = mentor_teacher
      @start_date = start_date
      @end_date = end_date
      @start_source_id = start_source_id
      @end_source_id = end_source_id
    end
  end
end

app/models/migration/participant_profile.rb
module Migration
  class ParticipantProfile < Migration::Base
    self.inheritance_column = nil

    belongs_to :teacher_profile
    belongs_to :school_cohort
    has_many :induction_records
    has_many :school_mentors # only ParticipantProfile::Mentor

    scope :ect, -> { where(type: "ParticipantProfile::ECT") }
    scope :mentor, -> { where(type: "ParticipantProfile::Mentor") }
    scope :ect_or_mentor, -> { ect.or(mentor) }

    def ect?
      type == "ParticipantProfile::ECT"
    end

    def mentor?
      type == "ParticipantProfile::Mentor"
    end
  end
end

app/models/migration/partnership.rb
module Migration
  class Partnership < Migration::Base
    belongs_to :school
    belongs_to :lead_provider
    belongs_to :delivery_partner
    belongs_to :cohort
  end
end

app/models/migration/provider_relationship.rb
module Migration
  class ProviderRelationship < Migration::Base
    default_scope { where(discarded_at: nil) }

    belongs_to :lead_provider
    belongs_to :delivery_partner
    belongs_to :cohort
  end
end

app/models/migration/schedule.rb
module Migration
  class Schedule < Migration::Base
    self.inheritance_column = nil

    belongs_to :cohort
  end
end

app/models/migration/school.rb
module Migration
  class School < Migration::Base
    has_many :school_cohorts
    has_many :partnerships
  end
end

app/models/migration/school_cohort.rb
module Migration
  class SchoolCohort < Migration::Base
    belongs_to :school
    belongs_to :cohort
    has_many :induction_programmes
    belongs_to :appropriate_body
  end
end

app/models/migration/school_mentor.rb
module Migration
  class SchoolMentor < Migration::Base
    belongs_to :participant_profile
    belongs_to :school
  end
end

app/models/migration/school_period.rb
module Migration
  # NOTE: this is a PORO to help with collating school period data when processing InductionRecords
  #       this was originally a Struct but have made it a class so that we can reference it in
  #       multiple places and make it easier to test the code that uses it
  class SchoolPeriod
    attr_accessor :urn, :start_date, :end_date, :start_source_id, :end_source_id

    def initialize(urn:, start_date:, end_date:, start_source_id:, end_source_id:)
      @urn = urn
      @start_date = start_date
      @end_date = end_date
      @start_source_id = start_source_id
      @end_source_id = end_source_id
    end
  end
end

app/models/migration/teacher_profile.rb
module Migration
  class TeacherProfile < Migration::Base
    belongs_to :user
    has_many :participant_profiles
  end
end

app/models/migration/training_period_data.rb
module Migration
  # NOTE: this is a PORO to help with collating training period data when processing InductionRecords
  #       this was originally a Struct but have made it a class so that we can reference it in
  #       multiple places and make it easier to test the code that uses it
  class TrainingPeriodData
    attr_accessor :training_programme, :lead_provider, :delivery_partner, :core_materials, :cohort_year,
                  :start_date, :end_date, :start_source_id, :end_source_id

    def initialize(training_programme:, lead_provider:, delivery_partner:, core_materials:,
                   cohort_year:, start_date:, end_date:, start_source_id:, end_source_id:)
      @training_programme = training_programme
      @lead_provider = lead_provider
      @delivery_partner = delivery_partner
      @core_materials = core_materials
      @cohort_year = cohort_year
      @start_date = start_date
      @end_date = end_date
      @start_source_id = start_source_id
      @end_source_id = end_source_id
    end
  end
end

app/models/migration/user.rb
module Migration
  class User < Migration::Base
    has_one :teacher_profile

    def self.with_trn(trn)
      joins(:teacher_profile).where(teacher_profile: { trn: }).first
    end
  end
end

app/views/migration/teachers/_ect_records.html.erb
<% if profile.present? %>
  <h3 class="govuk-heading-s">ECT records</h3>
  <% profile.induction_records.each do |record| %>
    <div class="migration-row">
      <div class="migration-column">
        <%= render Migration::InductionRecordComponent.new(induction_record: record) %>
      </div>
      <div class="migration-column">
        <%= render Migration::SchoolPeriodComponent.with_collection(record.ect_school_periods) %>
        <%= render Migration::TrainingPeriodComponent.with_collection(record.training_periods) %>
        <%= render Migration::MentorshipPeriodComponent.with_collection(record.mentorship_periods) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/migration/teachers/_failures.html.erb
<% if failures.present? %>
  <%= govuk_warning_text(text: "Some of this teacher's records could not be migrated") %>

  <%= render Migration::MigrationFailureComponent.with_collection(failures) %>
<% end %>

app/views/migration/teachers/_induction_record.html.erb
<%= govuk_summary_card(title: "Induction record (#{induction_record.participant_type})") do |card|
  card.with_summary_list(html_attributes: { class: "govuk-!-font-size-14" }) do |list|
    list.with_row do |row|
      row.with_key(text: "ID")
      row.with_value(text: induction_record.id)
    end
    attrs = {}
    attrs[:classes] = "matched" if matches.include?(:start_date)
    list.with_row(**attrs) do |row|
      row.with_key(text: "Start date")
      row.with_value(text: induction_record.pretty_start_date)
    end

    attrs = {}
    attrs[:classes] = "matched" if matches.include?(:end_date)
    list.with_row(**attrs) do |row|
      row.with_key(text: "End date")
      row.with_value(text: induction_record.pretty_end_date)
    end

    # TODO: we should check that this actually still matches
    attrs = {}
    attrs[:classes] = "matched" if matches.include?(:school)
    list.with_row(**attrs) do |row|
      row.with_key(text: "School")
      row.with_value(text: induction_record.school_name_and_urn)
    end
    list.with_row do |row|
      row.with_key(text: "Training type")
      row.with_value(text: induction_record.training_type)
    end
    list.with_row do |row|
      row.with_key(text: "Appropriate body")
      row.with_value(text: induction_record.appropriate_body_name)
    end
    if induction_record.fip?
      list.with_row do |row|
        row.with_key(text: "Lead provider")
        row.with_value(text: induction_record.lead_provider_name)
      end
      list.with_row do |row|
        row.with_key(text: "Delivery partner")
        row.with_value(text: induction_record.delivery_partner_name)
      end
    elsif induction_record.cip?
      list.with_row do |row|
        row.with_key(text: "Core materials provider")
        row.with_value(text: induction_record.cip_materials_name)
      end
    end
    list.with_row do |row|
      row.with_key(text: "Mentor")
      row.with_value(text: induction_record.mentor_name)
    end
    list.with_row do |row|
      row.with_key(text: "Record status")
      row.with_value(text: induction_record.induction_status)
    end
    list.with_row do |row|
      row.with_key(text: "Training status")
      row.with_value(text: induction_record.training_status)
    end
  end
end %>

app/views/migration/teachers/_mentor_records.html.erb
<% if profile.present? %>
  <h3 class="govuk-heading-s">Mentor records</h3>

  <% profile.induction_records.each do |record| %>
    <div class="migration-row">
      <div class="migration-column">
        <%= render Migration::InductionRecordComponent.new(induction_record: record) %>
      </div>
      <div class="migration-column">
        <% record.mentor_school_periods.each do |period| %>
          <%= render Migration::SchoolPeriodComponent.new(school_period: period) %>
        <% end %>
        <% record.training_periods.each do |period| %>
          <%= render Migration::TrainingPeriodComponent.new(training_period: period) %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/migration/teachers/_school_period.html.erb
<%= govuk_summary_card(title: "School period") do |card|
  card.with_summary_list(html_attributes: { class: "govuk-!-font-size-14" }) do |list|
    list.with_row do |row|
      row.with_key(text: "ID")
      row.with_value(text: school_period.id)
    end

    # TODO: we should check that this actually still matches
    attrs = {}
    attrs[:classes] = "matched" if matches.include?(:school)
    list.with_row(**attrs) do |row|
      row.with_key(text: "School")
      row.with_value(text: school_period.school_name_and_urn)
    end

    attrs = {}
    attrs[:classes] = "matched" if matches.include?(:started_on)
    list.with_row(**attrs) do |row|
      row.with_key(text: "Started on")
      row.with_value(text: school_period.started_on)
    end

    attrs = {}
    attrs[:classes] = "matched" if matches.include?(:finished_on)
    list.with_row(**attrs) do |row|
      row.with_key(text: "Finished on")
      row.with_value(text: "#{school_period.finished_on || ''}")
    end
  end
end %>

app/views/migration/teachers/_teacher.html.erb
<%= govuk_summary_card(title: "Teacher") do |card|
  card.with_summary_list(html_attributes: { class: "govuk-!-font-size-14" }) do |list|
    list.with_row do |row|
      row.with_key(text: "ID")
      row.with_value(text: teacher.id)
    end
    list.with_row do |row|
      row.with_key(text: "Full name")
      row.with_value(text: teacher.full_name)
    end
    list.with_row do |row|
      row.with_key(text: "TRN")
      row.with_value(text: teacher.trn)
    end
  end
end %>

app/views/migration/teachers/_user.html.erb
<%= govuk_summary_card(title: "User") do |card|
  card.with_summary_list(html_attributes: { class: "govuk-!-font-size-14" }) do |list|
    list.with_row do |row|
      row.with_key(text: "ID")
      row.with_value(text: user.id)
    end
    list.with_row do |row|
      row.with_key(text: "Full name")
      row.with_value(text: user.full_name)
    end
    list.with_row do |row|
      row.with_key(text: "TRN")
      row.with_value(text: user.teacher_profile.trn)
    end
    list.with_row do |row|
      row.with_key(text: "Email")
      row.with_value(text: user.email)
    end
  end
end %>

app/views/migration/teachers/index.html.erb
<% page_data(title: "Teachers") %>

<div class="search-box">
  <%= form_with method: :get, class: "search-box__form" do |f| %>
    <div class="search-box__input">
      <%= f.govuk_text_field(
        "q",
        value: params[:q],
        label: { text: "Search for teacher", size: "s" },
        hint: { text: "Name or TRN" },
      )
    %>
    </div>

    <%= f.govuk_submit "Search", classes: "search-box__button" %>
  <% end %>
</div>

<p class="govuk-body"><strong><%= @pagy.count %></strong> teachers found</p>

<%= govuk_table do |table|
  table.with_head do |head|
    head.with_row do |row|
      row.with_cell(text: "Name")
      row.with_cell(text: "TRN")
    end
  end

  table.with_body do |body|
    @teachers.each_with_index do |teacher, index|
      body.with_row do |row|
        row.with_cell do
          govuk_link_to "#{teacher.first_name} #{teacher.last_name}", teacher_path(teacher, page: @pagy.page)
        end
        row.with_cell(text: teacher.trn)
      end
    end
  end
end %>
<%== govuk_pagination pagy: @pagy %>

app/views/migration/teachers/show.html.erb
<% page_data(title: @teacher.full_name, backlink_href: admin_teacher_path(@teacher, page: @page)) %>

<div class="migration-row">
  <div class="migration-column">
    <%= render partial: "user", locals: { user: @user } %>
  </div>
  <div class="migration-column">
    <%= render partial: "teacher", locals: { teacher: @teacher } %>
  </div>
</div>

<%= render partial: "ect_records", locals: { profile: @ect_profile } %>
<%= render partial: "mentor_records", locals: { profile: @mentor_profile } %>
<%= render partial: "failures", locals: { failures: @failures } %>